export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const APPROVE_USERS = 'APPROVE_USERS';
export const REJECT_USERS = 'REJECT_USERS';

export const LOADING_USERS = 'LOADING_USERS';